# Generated by Django

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0023_alter_folder_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Designates whether the user is an admin.', verbose_name='Admin Status'),
        ),
        migrations.CreateModel(
            name='FeatureToggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='Feature Key')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('parent_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Parent Key')),
                ('enabled_for_admin', models.BooleanField(default=True, verbose_name='Enabled for Admin')),
                ('enabled_for_user', models.BooleanField(default=True, verbose_name='Enabled for User')),
                ('user_exceptions', models.ManyToManyField(blank=True, help_text='Specific users who have access to this feature overriding the role defaults.', to=settings.AUTH_USER_MODEL, verbose_name='User Exceptions')),
            ],
            options={
                'verbose_name': 'Feature Toggle',
                'verbose_name_plural': 'Feature Toggles',
            },
        ),
    ]
