# Generated by Django 6.0.6 on 2026-07-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0024_featuretoggle_user_is_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scimtoken',
            options={'verbose_name': 'SCIM Token', 'verbose_name_plural': 'SCIM Tokens'},
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Designates that this user has administrative access to the platform, subject to feature toggles.', verbose_name='admin status'),
        ),
    ]
