# Generated by Django 6.0.6 on 2026-07-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0025_alter_scimtoken_options_alter_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='platform_role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Admin'), ('user', 'User')], default='user', help_text='The 3-tier global role for the user: superadmin, admin, or user.', max_length=20, verbose_name='Platform Role'),
        ),
    ]
