# Generated by Django 5.1.1 on 2024-09-12 15:00

import django.db.models.deletion
import iam.models
from django.db import migrations, models


def safe_alter_folder_field(apps, schema_editor):
    if "mssql" in schema_editor.connection.vendor:
        pass


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("global_settings", "0001_initial"),
        ("iam", "0006_alter_role_folder_alter_roleassignment_folder_and_more"),
    ]

    operations = [
        migrations.RunPython(safe_alter_folder_field, reverse_code=migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="globalsettings",
                    name="folder",
                    field=models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
