# Migration: Replace Qualification with Terminology for Incident & RiskScenario.qualifications
# Generated by Django 5.1.10 on 2025-09-10 14:49

from django.db import migrations, models


def safe_mssql_migration(apps, schema_editor):
    if schema_editor.connection.vendor in ("microsoft", "mssql"):
        with schema_editor.connection.cursor() as cursor:
            # Drop legacy columns if present
            cursor.execute("""
            IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('core_incident') AND name = 'qualifications')
            BEGIN
                ALTER TABLE core_incident DROP COLUMN qualifications;
            END;
            IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('core_riskscenario') AND name = 'qualifications')
            BEGIN
                ALTER TABLE core_riskscenario DROP COLUMN qualifications;
            END;
            IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'core_incident_qualifications')
            BEGIN
                CREATE TABLE core_incident_qualifications (
                    id BIGINT IDENTITY(1,1) PRIMARY KEY,
                    incident_id BIGINT NOT NULL,
                    terminology_id BIGINT NOT NULL
                );
            END;
            IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'core_riskscenario_qualifications')
            BEGIN
                CREATE TABLE core_riskscenario_qualifications (
                    id BIGINT IDENTITY(1,1) PRIMARY KEY,
                    riskscenario_id BIGINT NOT NULL,
                    terminology_id BIGINT NOT NULL
                );
            END;
            """)


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("core", "0093_alter_asset_parent_assets"),
    ]

    operations = [
        migrations.RunPython(safe_mssql_migration, reverse_code=migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="incident",
                    name="qualifications",
                ),
                migrations.AddField(
                    model_name="incident",
                    name="qualifications",
                    field=models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"field_path": "qualifications", "is_visible": True},
                        related_name="incidents_qualifications",
                        to="core.terminology",
                        verbose_name="Qualifications",
                    ),
                ),
                migrations.RemoveField(
                    model_name="riskscenario",
                    name="qualifications",
                ),
                migrations.AddField(
                    model_name="riskscenario",
                    name="qualifications",
                    field=models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"field_path": "qualifications", "is_visible": True},
                        related_name="risk_scenarios_qualifications",
                        to="core.terminology",
                        verbose_name="Qualifications",
                    ),
                ),
                migrations.AlterField(
                    model_name="terminology",
                    name="field_path",
                    field=models.CharField(
                        choices=[
                            ("ro_to.risk_origin", "ro_to/risk_origin"),
                            ("qualifications", "qualifications"),
                        ],
                        max_length=100,
                        verbose_name="Field path",
                    ),
                ),
            ],
            database_operations=[],
        )
    ]
