# Generated by Django 6.0.6 on 2026-07-20 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0176_librarydraft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirementassessment',
            name='respondent_alignment',
        ),
        migrations.DeleteModel(
            name='PresetJourneyStep',
        ),
        migrations.DeleteModel(
            name='PresetJourney',
        ),
    ]
