# Generated by Django 6.0.6 on 2026-07-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0179_complianceassessment_scope_mode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complianceassessment",
            name="audit_period_year",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Audit period"
            ),
        ),
    ]
